### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by lyricalpolymath** [boxxa/meteor-polymer#1]
Hello
I've installed both your packages boxxa:polymer and boxxa:polymer-elements but they don't seem to be doing anything.

I'd expect that they'd run bower for me and download all components into public/bower_components
but that doesn't happen
nor it creates the polyfill

I've had to use 
`bower install --save Polymer/polymer` 
anyways

I don't understand what they really do
can you please explain a bit better how to install and use them?

**Comment by boxxa** [comment]
This runs the bower parts for you. When you install boxxa:polymer and boxxa:polymer-elements, it will load it up. Run meteor and you will see bower create your public directory and place the polymer components in there as you would see if you run bower. 

After that, you can import your elements and use normally. Here is a Gist using core scaffold
https://gist.github.com/boxxa/0aa1c3e5f3beafec6dc7

**Comment by lyricalpolymath** [comment]
hey... now it works... I don't know what was wrong.. but when I first installed them and run the app they didn't work.  neither the polyfill would  be loaded into the head tag, nor the components would be downloaded to the public/bower_components 

preety weird. anyways now it seems to work fine
thanks
