### ISSUE TITLE
Reinitialize Issue

### ISSUE THREAD

**Issue by CheoWalker** [boxxa/meteor-polymer#3]
Every time I run meteor I get these 2:
I20150222-01:15:50.324(-5)? Polymer exist already. To reinitialize, remove bower_components from your public/ folder
I20150222-01:15:51.179(-5)? Polymer-elements exist already. To reinitialize, remove bower_components from your public/ folder

It is very strange.

**Comment by boxxa** [comment]
This is related to some debugging lines added. If it detected you already have polymer downloaded, it will write this to let you know and not re download.

**Comment by CheoWalker** [comment]
I just saw it, nvm.
