### ISSUE TITLE
Polymer 1.0 support?

### ISSUE THREAD

**Issue by Pickachu** [boxxa/meteor-polymer#4]
https://www.polymer-project.org/1.0/

**Comment by boxxa** [comment]
It will be out this weekend. I am out of town but saw the release so both versions will be available in my package.

**Comment by luccamordente** [comment]
Awesome! :+1: 
Waiting for that :)

**Comment by boxxa** [comment]
Fixed

**Comment by luccamordente** [comment]
Thanks @boxxa !
