### ISSUE TITLE
Testing in windows 7

### ISSUE THREAD

**Issue by alexofob** [boxxa/meteor-polymer#5]
Hi there,

I am testing this package on a windows 7 machine, and after installing the package and starting meteor, this is the error message I am getting:

=> Exited with code: 8
W20150606-19:09:04.139(0)? (STDERR) 
W20150606-19:09:04.141(0)? (STDERR) C:.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
W20150606-19:09:04.141(0)? (STDERR)                                             throw(ex);
W20150606-19:09:04.141(0)? (STDERR)                                                   ^
W20150606-19:09:04.142(0)? (STDERR) TypeError: Arguments to path.resolve must be strings
W20150606-19:09:04.142(0)? (STDERR)     at Object.exports.resolve (path.js:116:15)
W20150606-19:09:04.142(0)? (STDERR)     at Object.exports.relative (path.js:240:18)
W20150606-19:09:04.142(0)? (STDERR)     at Package (packages/boxxa:polymer/boxxa:polymer.js:21:1)

Kindly suggest what could be wrong.

**Comment by boxxa** [comment]
I have been testing this and it is a known bug. The way it user Bower on Windows is causing issues from what I can tell.

**Comment by Akash-dvd** [comment]
I am also getting the same issue.
Plz resolve asap

**Comment by boxxa** [comment]
Sorry my primary build is Mac. I don't have a windows platform for this currently.

**Comment by tsamatech** [comment]
Did u support for ubuntu ?

**Comment by boxxa** [comment]
You can try it. If bower doesn't install then it will break. I only build on my MacBook
